/**
 * Rebuilds src/webawesome/vendor/webawesome.bundle.js.
 *
 * The design system ships element definitions as a self-contained bundle so
 * consumers need neither an npm install nor a JavaScript CDN. Web Awesome is
 * a devDependency here purely as the build input.
 *
 * Run after bumping the pinned Web Awesome version:
 *   bun scripts/build-vendor.ts
 */
import { readdirSync, existsSync, writeFileSync } from "node:fs";

/** Keep in sync with FONT_AWESOME_VERSION in src/webawesome/setup.tsx. */
const FONT_AWESOME_VERSION = "7.3.1";
const ICON_PATH = `https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@${FONT_AWESOME_VERSION}/svgs`;

const COMPONENTS_DIR = "node_modules/@awesome.me/webawesome/dist/components";
const ENTRY = "scripts/vendor-entry.js";
const OUT = "src/webawesome/vendor/webawesome.bundle.js";

const names = readdirSync(COMPONENTS_DIR)
  .filter((name) => existsSync(`${COMPONENTS_DIR}/${name}/${name}.js`))
  .sort();

const entry = [
  "// Auto-generated by scripts/build-vendor.ts — do not edit.",
  // Pin the icon path BEFORE any component registers: Web Awesome's default
  // resolver hardcodes an older Font Awesome release that 403s for icons
  // added since, and the first <wa-icon> resolves as soon as it upgrades.
  `import { setIconPath } from "@awesome.me/webawesome/dist/webawesome.js";`,
  `setIconPath(${JSON.stringify(ICON_PATH)});`,
  ...names.map(
    (name) => `import "@awesome.me/webawesome/dist/components/${name}/${name}.js";`,
  ),
  `export * from "@awesome.me/webawesome/dist/webawesome.js";`,
  "",
].join("\n");

writeFileSync(ENTRY, entry);

const build = Bun.spawnSync([
  "bun",
  "build",
  ENTRY,
  `--outfile=${OUT}`,
  "--format=esm",
  "--target=browser",
  "--minify",
]);

process.stdout.write(build.stdout.toString());
process.stderr.write(build.stderr.toString());

if (build.exitCode !== 0) process.exit(build.exitCode ?? 1);
console.log(`bundled ${names.length} Web Awesome components into ${OUT}`);
