/**
 * Rebuilds the vendored Web Awesome bundles:
 *   src/webawesome/vendor/webawesome.bundle.js      (default)
 *   src/webawesome/vendor/webawesome.ssr.bundle.js  (hydration-aware)
 *
 * The design system ships element definitions as self-contained bundles so
 * consumers need neither an npm install nor a JavaScript CDN. Web Awesome is
 * a devDependency here purely as the build input.
 *
 * The SSR bundle is identical except that Lit's hydration support is imported
 * BEFORE any component, which is what Web Awesome's SSR docs require so
 * server-rendered declarative shadow roots hydrate instead of being replaced.
 *
 * Run after bumping the pinned Web Awesome version:
 *   bun scripts/build-vendor.ts
 */
import { readdirSync, existsSync, writeFileSync } from "node:fs";

/** Keep in sync with FONT_AWESOME_VERSION in src/webawesome/setup.tsx. */
const FONT_AWESOME_VERSION = "7.3.1";
const ICON_PATH = `https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@${FONT_AWESOME_VERSION}/svgs`;

const COMPONENTS_DIR = "node_modules/@awesome.me/webawesome/dist/components";

const names = readdirSync(COMPONENTS_DIR)
  .filter((name) => existsSync(`${COMPONENTS_DIR}/${name}/${name}.js`))
  .sort();

interface Target {
  entry: string;
  out: string;
  hydrate: boolean;
}

const targets: Target[] = [
  { entry: "scripts/vendor-entry.js", out: "src/webawesome/vendor/webawesome.bundle.js", hydrate: false },
  {
    entry: "scripts/vendor-entry.ssr.js",
    out: "src/webawesome/vendor/webawesome.ssr.bundle.js",
    hydrate: true,
  },
];

for (const target of targets) {
  const entry = [
    "// Auto-generated by scripts/build-vendor.ts — do not edit.",
    // Hydration support must come first, before any component is imported.
    ...(target.hydrate
      ? [`import "@lit-labs/ssr-client/lit-element-hydrate-support.js";`]
      : []),
    // Pin the icon path BEFORE any component registers: Web Awesome's default
    // resolver hardcodes an older Font Awesome release that 403s for icons
    // added since, and the first <wa-icon> resolves as soon as it upgrades.
    `import { setIconPath } from "@awesome.me/webawesome/dist/webawesome.js";`,
    `setIconPath(${JSON.stringify(ICON_PATH)});`,
    ...names.map(
      (name) => `import "@awesome.me/webawesome/dist/components/${name}/${name}.js";`,
    ),
    `export * from "@awesome.me/webawesome/dist/webawesome.js";`,
    "",
  ].join("\n");

  writeFileSync(target.entry, entry);

  const build = Bun.spawnSync([
    "bun",
    "build",
    target.entry,
    `--outfile=${target.out}`,
    "--format=esm",
    "--target=browser",
    "--minify",
  ]);

  process.stdout.write(build.stdout.toString());
  process.stderr.write(build.stderr.toString());

  if (build.exitCode !== 0) process.exit(build.exitCode ?? 1);
  console.log(`bundled ${names.length} Web Awesome components into ${target.out}`);
}
